In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
df_train = pd.read_json("dataset/train.jsonl", lines=True)
df_test = pd.read_json("dataset/test.jsonl", lines=True)

In [27]:
df_train

,qid,scenario,question,ground_truth,student_incorrect_solution,student_profile,teacher_described_confusion,self-correctness,self-typical-confusion,self-typical-interactions,conversation
0,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some..."
1,5000084,2,John is very unfit and decides to work up to d...,He needs to do 15*3=45 progressions\nThat will...,"To get to 15 reps, John will take 15 - 1 = 14 ...",Stephanie is a 7th grade student. She has diff...,She became fixated on a wrong calculation and ...,No,2.0,2.0,"Teacher: (probing)Stephanie, How many days wil..."
2,5000982,3,James has 20 pairs of red socks and half as ma...,He has 20/2=10 black socks\nSo he has 20+10=30...,James has 20/2 = 10 pairs of black socks.\nJam...,DeAndre is a 7th grade student. He has problem...,He was technically correct.,Yes,5.0,5.0,"Teacher: (probing)DeAndre, you successfully an..."
3,5000274,4,Jason drives past 3 convenience stores on his ...,First find the additional distance between the...,The distance between the second store and thir...,Winnie is a 7th grade student. She struggle to...,He understood it when it was broken down step ...,Yes,3.0,3.0,Teacher: (probing)What is the distance between...
4,5000797,5,Wanda walks her daughter .5 miles to school in...,She walks .5 miles to school and back 4 times ...,"Every day, Wanda walks a total of 0.5 + 0.5 = ...",Cody is a 7th grade student. He has problem wi...,He forgot she walked twice each day!,Yes,3.0,3.0,"Teacher: (probing)Cody, How far doe Wanda walk..."
...,...,...,...,...,...,...,...,...,...,...,...
2257,5000895,4,Greta worked 40 hours and was paid $12 per hou...,"For the 40 hours worked, Greta earned a total ...",Greta earned 40 x $12 = $480 for 40 hours of w...,Mariana is a 7th grade student. She struggle t...,They just needed to divide $480 by $15 per hour,Yes,3.0,3.0,Teacher: (generic)Hi Mariana can you explain y...
2258,5000596,5,"In four years, Suzy will be twice Mary's age t...","In four years, Suzy will be 20+4=24.\nThen Mar...",Let's start by finding out how old Suzy will b...,Winnie is a 7th grade student. She has problem...,They needed to work out how old she is now,Yes,3.0,3.0,Teacher: (generic)Hi Winnie can you explain yo...
2259,5000862,1,James supercharges his car which increases his...,He increased his speed by 150*.3=45 mph\nSo hi...,"First, we need to find out how much the superc...",Riya is a 7th grade student. She struggle most...,had confused the 15% weight decrease with a 15...,Yes,5.0,5.0,"Teacher: (generic)Morning Riya, can you talk m..."
2260,5000171,2,James turned 23 the same time John turned 35. ...,James is 35-23=12 years younger than John\n5 y...,The difference in age between James and John i...,Mariana is a 7th grade student. She has proble...,the student had subtracted 5 instead of adding 5,Yes,5.0,5.0,"Teacher: (generic)Morning Mariana, can you tal..."
2261,5000143,3,Two vampires have come to the sleepy village o...,First find the number of new vampires after on...,"After the first night, each vampire will have ...",Lakisha is a 7th grade student. She has proble...,they seemed to findamentally misunderstand wha...,Yes,2.0,2.0,"Teacher: (generic)Morning Lakisha, can you tal..."

In [28]:
df_train["conversation"][0]

'Teacher: (probing)Steven, If you had 4 of something and tripled that amount, how much would you have?|EOM|Steven: I would have 12 of something.|EOM|Teacher: (probing)So if Nancy triples the 18 cubic feet of water, how much would she have?|EOM|Steven: She would have 54 cubic feet of water.|EOM|Teacher: (generic)Exactly correct!'

In [29]:
df_train["conversation"][0].split("|EOM|")

['Teacher: (probing)Steven, If you had 4 of something and tripled that amount, how much would you have?',
 'Steven: I would have 12 of something.',
 'Teacher: (probing)So if Nancy triples the 18 cubic feet of water, how much would she have?',
 'Steven: She would have 54 cubic feet of water.',
 'Teacher: (generic)Exactly correct!']

In [30]:
df_train["student_profile"]

0       Steven is a 7th grade student. He has difficul...
1       Stephanie is a 7th grade student. She has diff...
2       DeAndre is a 7th grade student. He has problem...
3       Winnie is a 7th grade student. She struggle to...
4       Cody is a 7th grade student. He has problem wi...
                              ...
2257    Mariana is a 7th grade student. She struggle t...
2258    Winnie is a 7th grade student. She has problem...
2259    Riya is a 7th grade student. She struggle most...
2260    Mariana is a 7th grade student. She has proble...
2261    Lakisha is a 7th grade student. She has proble...
Name: student_profile, Length: 2262, dtype: object

In [31]:
df_train["qid"].unique().shape

(1035,)

In [32]:
df_train.dtypes

qid                              int64
scenario                         int64
question                        object
ground_truth                    object
student_incorrect_solution      object
student_profile                 object
teacher_described_confusion     object
self-correctness                object
self-typical-confusion         float64
self-typical-interactions      float64
conversation                    object
dtype: object

In [33]:
df_train["student_profile"]

0       Steven is a 7th grade student. He has difficul...
1       Stephanie is a 7th grade student. She has diff...
2       DeAndre is a 7th grade student. He has problem...
3       Winnie is a 7th grade student. She struggle to...
4       Cody is a 7th grade student. He has problem wi...
                              ...
2257    Mariana is a 7th grade student. She struggle t...
2258    Winnie is a 7th grade student. She has problem...
2259    Riya is a 7th grade student. She struggle most...
2260    Mariana is a 7th grade student. She has proble...
2261    Lakisha is a 7th grade student. She has proble...
Name: student_profile, Length: 2262, dtype: object

In [34]:
df_train["self-correctness"].value_counts()

self-correctness
Yes                                    1696
Yes, but I had to reveal the answer     303
No                                      254
Name: count, dtype: int64

In [35]:
df = pd.concat([df_train, df_test], axis=0, ignore_index=True)
df

,qid,scenario,question,ground_truth,student_incorrect_solution,student_profile,teacher_described_confusion,self-correctness,self-typical-confusion,self-typical-interactions,conversation
0,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some..."
1,5000084,2,John is very unfit and decides to work up to d...,He needs to do 15*3=45 progressions\nThat will...,"To get to 15 reps, John will take 15 - 1 = 14 ...",Stephanie is a 7th grade student. She has diff...,She became fixated on a wrong calculation and ...,No,2.0,2.0,"Teacher: (probing)Stephanie, How many days wil..."
2,5000982,3,James has 20 pairs of red socks and half as ma...,He has 20/2=10 black socks\nSo he has 20+10=30...,James has 20/2 = 10 pairs of black socks.\nJam...,DeAndre is a 7th grade student. He has problem...,He was technically correct.,Yes,5.0,5.0,"Teacher: (probing)DeAndre, you successfully an..."
3,5000274,4,Jason drives past 3 convenience stores on his ...,First find the additional distance between the...,The distance between the second store and thir...,Winnie is a 7th grade student. She struggle to...,He understood it when it was broken down step ...,Yes,3.0,3.0,Teacher: (probing)What is the distance between...
4,5000797,5,Wanda walks her daughter .5 miles to school in...,She walks .5 miles to school and back 4 times ...,"Every day, Wanda walks a total of 0.5 + 0.5 = ...",Cody is a 7th grade student. He has problem wi...,He forgot she walked twice each day!,Yes,3.0,3.0,"Teacher: (probing)Cody, How far doe Wanda walk..."
...,...,...,...,...,...,...,...,...,...,...,...
2856,5000286,5,Tom's cat needs an expensive surgery. He has ...,The insurance cost 24*20=$480\nWith insurance ...,Tom paid a total of 24 x $20 = $480 for pet in...,Luca is a 7th grade student. He has problem wi...,The student forgot to add the cost of insuranc...,Yes,4.0,4.0,"Teacher: (generic)Hi Luca, can you tell me how..."
2857,5000847,1,Jimmy wants to play in the inflatable swimming...,It will take 84 / 2 = 42 trips to fill the poo...,"To fill the pool with 84 gallons of water, Jim...",Ronny is a 7th grade student. He struggle to p...,Conceptual error in third step. calculated tim...,Yes,3.0,3.0,"Teacher: (generic)Hi , could you please walk m..."
2858,5000818,2,A restaurant buffet has 36 different dishes av...,There are fresh mangos in 36 / 6 = 6 dishes.\n...,There are 3 + 36/6 + 1 = 10 dishes with mango ...,Winnie is a 7th grade student. She struggle mo...,Repeated subtraction by deducting the number o...,Yes,3.0,3.0,"Teacher: (generic)Hi, could you please walk me..."
2859,5000134,3,Jeff committed to run for an hour a day during...,Jeff was able to run a total of 60 x 3 = 180 m...,Jeff runs for 1 hour x 5 days = 5 hours from M...,Scott is a 7th grade student. He has problem w...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me..."
2860,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me..."

In [36]:
df.shape

(2861, 11)

In [39]:
sample = df["conversation"][0]
sample

'Teacher: (probing)Steven, If you had 4 of something and tripled that amount, how much would you have?|EOM|Steven: I would have 12 of something.|EOM|Teacher: (probing)So if Nancy triples the 18 cubic feet of water, how much would she have?|EOM|Steven: She would have 54 cubic feet of water.|EOM|Teacher: (generic)Exactly correct!'

In [40]:
sample.split("|EOM|")

['Teacher: (probing)Steven, If you had 4 of something and tripled that amount, how much would you have?',
 'Steven: I would have 12 of something.',
 'Teacher: (probing)So if Nancy triples the 18 cubic feet of water, how much would she have?',
 'Steven: She would have 54 cubic feet of water.',
 'Teacher: (generic)Exactly correct!']

In [57]:
l = []
l.append("1")
l

['1']

In [65]:
l = ["0","1","2","3"]

"|EOM|".join(l[1:4])

'1|EOM|2|EOM|3'

In [88]:
def form_state_action_pair(conversation):
    samples = conversation.split("|EOM|")
    # samples.insert(0, "START")

    output = ["START"]

    i = 0
    while i < len(samples):
        if samples[i][:7] == "Teacher":
            # add an NaN state between actions
            if output[-1][:7] == "Teacher":
                output.append(np.nan)
            output.append(samples[i])
            i = i+1
        else:
            # find next teacher sentence
            teacher_index = i
            while teacher_index < len(samples): 
                if samples[teacher_index][:7] == "Teacher":
                    break
                teacher_index = teacher_index + 1

            state = "|EOM|".join(samples[i:teacher_index])
            output.append(state)
            i = teacher_index

    if output[-1][:7] != "Teacher":
        output.append(np.nan)
    return output

In [89]:
df_output = pd.DataFrame(columns=['qid', 'scenario', 'question', 'ground_truth',
       'student_incorrect_solution', 'student_profile',
       'teacher_described_confusion', 'self-correctness',
       'self-typical-confusion', 'self-typical-interactions', 'conversation',
        "state", "action_type", "action_text", "reward", "next_state", "next_action_type", "next_action_text", "done"
                                 ])
df_output

for index, row in df.iterrows():
    pairs = form_state_action_pair(row["conversation"])

    assert len(pairs) % 2 == 0
    
    for i in range(0, len(pairs),2):
        # student
        if not pd.isnull(pairs[i]):
            assert pairs[i][:7] != "Teacher"
        state = pairs[i]
        
        if pd.isnull(pairs[i+1]):
            action_type = np.nan
            action_text = np.nan
        else:
            # teacher
            s = pairs[i+1]
            assert s[:7] == "Teacher"
            action_type = s[s.find("(")+1:s.find(")")]
            action_text = s
        
        reward = np.nan

        if i == len(pairs) - 2:
            next_state = np.nan
            next_action_type = np.nan
            next_action_text = np.nan
            done = 1
        else:
            # student
            if pd.isnull(pairs[i+2]):
                next_state = np.nan
            else:
                assert pairs[i+2][:7] != "Teacher"
                next_state = pairs[i+2]
            
            # teacher
            if pd.isnull(pairs[i+3]):
                next_action_type = np.nan
                next_action_text = np.nan
            else:
                assert pairs[i+3][:7] == "Teacher"
                s = pairs[i+3]
                next_action_type = s[s.find("(")+1:s.find(")")]
                next_action_text = s
            done = 0
        
        
        df_output.loc[len(df_output)] = \
                                        [row["qid"],
                                        row["scenario"],
                                        row["question"],
                                        row["ground_truth"],
                                        row["student_incorrect_solution"],
                                        row["student_profile"],
                                        row["teacher_described_confusion"],
                                        row["self-correctness"],
                                        row["self-typical-confusion"],
                                        row["self-typical-interactions"],
                                        row["conversation"],
                                        state, 
                                        action_type, 
                                        action_text, 
                                        reward, 
                                        next_state, 
                                        next_action_type, 
                                        next_action_text, 
                                        done
                                        ]

In [90]:
df_output

,qid,scenario,question,ground_truth,student_incorrect_solution,student_profile,teacher_described_confusion,self-correctness,self-typical-confusion,self-typical-interactions,conversation,state,action_type,action_text,reward,next_state,next_action_type,next_action_text,done
0,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some...",START,probing,"Teacher: (probing)Steven, If you had 4 of some...",NaN,Steven: I would have 12 of something.,probing,Teacher: (probing)So if Nancy triples the 18 c...,0
1,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some...",Steven: I would have 12 of something.,probing,Teacher: (probing)So if Nancy triples the 18 c...,NaN,Steven: She would have 54 cubic feet of water.,generic,Teacher: (generic)Exactly correct!,0
2,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some...",Steven: She would have 54 cubic feet of water.,generic,Teacher: (generic)Exactly correct!,NaN,NaN,NaN,NaN,1
3,5000084,2,John is very unfit and decides to work up to d...,He needs to do 15*3=45 progressions\nThat will...,"To get to 15 reps, John will take 15 - 1 = 14 ...",Stephanie is a 7th grade student. She has diff...,She became fixated on a wrong calculation and ...,No,2.0,2.0,"Teacher: (probing)Stephanie, How many days wil...",START,probing,"Teacher: (probing)Stephanie, How many days wil...",NaN,"Student: It will take one day to do one step, ...",probing,Teacher: (probing)So how many days will it tak...,0
4,5000084,2,John is very unfit and decides to work up to d...,He needs to do 15*3=45 progressions\nThat will...,"To get to 15 reps, John will take 15 - 1 = 14 ...",Stephanie is a 7th grade student. She has diff...,She became fixated on a wrong calculation and ...,No,2.0,2.0,"Teacher: (probing)Stephanie, How many days wil...","Student: It will take one day to do one step, ...",probing,Teacher: (probing)So how many days will it tak...,NaN,Student: It will take 15 days to do 15 wall pu...,probing,Teacher: (probing)How many days to get to 15 h...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20149,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...","Student: Sure, I said that 75% of the cars hav...",focus,Teacher: (focus)That doesn't seem to be correc...,NaN,Student: Sure. I said that 75% of the cars hav...,focus,Teacher: (focus)Great. The question now says t...,0
20150,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...",Student: Sure. I said that 75% of the cars hav...,focus,Teacher: (focus)Great. The question now says t...,NaN,"Student: Yes, 1/5th of 225 cars is (1/5)*225 =...",focus,Teacher: (focus)That's wonderful. So now what ...,0
20151,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...","Student: Yes, 1/5th of 225 cars is (1/5)*225 =...",focus,Teacher: (focus)That's wonderful. So now what ...,NaN,Student: There are 225 cars with valid tickets...,generic,Teacher: (generic)There's your answer. I hope ...,0
20152,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...",Student: There are 225 cars with valid tickets...,generic,Teacher: (generic)There's your answer. I hope ...,NaN,"Student: Yes, I got it. Thanks for your help!",NaN,NaN,0
20153,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...","Student: Yes, I got it. Thanks for your help!",NaN,NaN,NaN,NaN,NaN,NaN,1

In [50]:
for i in ['qid', 'scenario', 'question', 'ground_truth',
       'student_incorrect_solution', 'student_profile',
       'teacher_described_confusion', 'self-correctness',
       'self-typical-confusion', 'self-typical-interactions', 'conversation']:
    print("row[\"{}\"]".format(i), end=",\n")

row["qid"],
row["scenario"],
row["question"],
row["ground_truth"],
row["student_incorrect_solution"],
row["student_profile"],
row["teacher_described_confusion"],
row["self-correctness"],
row["self-typical-confusion"],
row["self-typical-interactions"],
row["conversation"],

In [45]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [55]:
"Teacher"[:7]

'Teacher'

In [82]:
print(", \n".join(["state", "action_type", "action_text", "reward", "next_state", "next_action_type", "next_action_text", "done"]))

state,
action_type,
action_text,
reward,
next_state,
next_action_type,
next_action_text,
done

In [94]:
df_output.to_pickle("dataset/processed.pkl")

In [92]:
# loading dataset
# loaded_df = pd.read_pickle("./processed.pkl")

In [95]:
df_output

,qid,scenario,question,ground_truth,student_incorrect_solution,student_profile,teacher_described_confusion,self-correctness,self-typical-confusion,self-typical-interactions,conversation,state,action_type,action_text,reward,next_state,next_action_type,next_action_text,done
0,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some...",START,probing,"Teacher: (probing)Steven, If you had 4 of some...",NaN,Steven: I would have 12 of something.,probing,Teacher: (probing)So if Nancy triples the 18 c...,0
1,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some...",Steven: I would have 12 of something.,probing,Teacher: (probing)So if Nancy triples the 18 c...,NaN,Steven: She would have 54 cubic feet of water.,generic,Teacher: (generic)Exactly correct!,0
2,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some...",Steven: She would have 54 cubic feet of water.,generic,Teacher: (generic)Exactly correct!,NaN,NaN,NaN,NaN,1
3,5000084,2,John is very unfit and decides to work up to d...,He needs to do 15*3=45 progressions\nThat will...,"To get to 15 reps, John will take 15 - 1 = 14 ...",Stephanie is a 7th grade student. She has diff...,She became fixated on a wrong calculation and ...,No,2.0,2.0,"Teacher: (probing)Stephanie, How many days wil...",START,probing,"Teacher: (probing)Stephanie, How many days wil...",NaN,"Student: It will take one day to do one step, ...",probing,Teacher: (probing)So how many days will it tak...,0
4,5000084,2,John is very unfit and decides to work up to d...,He needs to do 15*3=45 progressions\nThat will...,"To get to 15 reps, John will take 15 - 1 = 14 ...",Stephanie is a 7th grade student. She has diff...,She became fixated on a wrong calculation and ...,No,2.0,2.0,"Teacher: (probing)Stephanie, How many days wil...","Student: It will take one day to do one step, ...",probing,Teacher: (probing)So how many days will it tak...,NaN,Student: It will take 15 days to do 15 wall pu...,probing,Teacher: (probing)How many days to get to 15 h...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20149,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...","Student: Sure, I said that 75% of the cars hav...",focus,Teacher: (focus)That doesn't seem to be correc...,NaN,Student: Sure. I said that 75% of the cars hav...,focus,Teacher: (focus)Great. The question now says t...,0
20150,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...",Student: Sure. I said that 75% of the cars hav...,focus,Teacher: (focus)Great. The question now says t...,NaN,"Student: Yes, 1/5th of 225 cars is (1/5)*225 =...",focus,Teacher: (focus)That's wonderful. So now what ...,0
20151,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...","Student: Yes, 1/5th of 225 cars is (1/5)*225 =...",focus,Teacher: (focus)That's wonderful. So now what ...,NaN,Student: There are 225 cars with valid tickets...,generic,Teacher: (generic)There's your answer. I hope ...,0
20152,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...",Student: There are 225 cars with valid tickets...,generic,Teacher: (generic)There's your answer. I hope ...,NaN,"Student: Yes, I got it. Thanks for your help!",NaN,NaN,0
20153,5000275,4,Andy is checking to see if all the cars in the...,First find how many cars have valid tickets: 7...,"75% of the cars have valid tickets, so 100%-75...",Stephanie is a 7th grade student. She struggle...,None,None,NaN,NaN,"Teacher: (generic)Hi, could you please walk me...","Student: Yes, I got it. Thanks for your help!",NaN,NaN,NaN,NaN,NaN,NaN,1

In [99]:
df_output.to_excel("dataset/processed.xlsx")